db:
  image: sameersbn/postgresql:9.1-1
  environment:
    - DB_USER=docs
    - DB_PASS=secretpassword
    - DB_NAME=docs
  volumes:
    - ./pgsql:/var/lib/postgresql
  ports:
    - "5432:5432"
readthedocs:
  build: .
  environment:
    - DB_USER=docs
    - DB_PASS=secretpassword
    - DB_NAME=docs
    #- DB_PORT_NUM=5432
  ports:
    - "8000:8000"
  links:
    - db
    - elasticsearch
    - redis
  volumes:
    - ./user_builds:/app/user_builds
elasticsearch:
  image: jfroche/elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - ./es:/var/lib/elasticsearch
redis:
  image: redis
build:
  image: readthedocs/build

